server:
  port: 8080
  context-path: /
spring:
   datasource:
     driver-class-name: com.mysql.jdbc.Driver
     username: root
     password: root
     url: jdbc:mysql://localhost:3306/emall?useSSL=false
     type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  type-aliases-package: org.web.emall.models
  mapper-locations: classpath:mybatis/*.xml
  config-location: classpath:mybatis-config.xml